name: e2e

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Running smoke tests
        run: npm run serenity

      - name: GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        if: matrix.node-version == '18.x' && github.ref == 'refs/heads/master'
        with:
          BRANCH: gh-pages
          FOLDER: target/site/serenity
          CLEAN: true
